APPLICATION_TITLE "Device Manager"
APPLICATION_VERSION_MAJOR 0
APPLICATION_VERSION_MINOR 1
APPLICATION_ICON $APP_ICON_NAME PATH /system/graphics/icons/device_manager.tga
WINDOW_TITLE "Device Manager"
